version: '3.1'

services:
    db:
        image: mysql:8.0.1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: comment_section
        ports:
            - '3306:3306'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '8080:80'

    client:
        build:
            context: ./client
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
    server:
        build:
            context: ./server
        volumes:
            - ./server:/app
            - /app/node_modules
        ports:
            - '3500:3500'
        environment:
            DB_NAME: comment_section
            DB_USER: root
            DB_PASSWORD: root
            ACCESS_TOKEN_SECRET: 7yehb33fdc16165c690e4c9827ed0ecd867466e8026e31966e0244df7ec1750268606122c510d70e2336fd4f24243cb30102630268de1a4be4c609e865c36396
            REFRESH_TOKEN_SECRET: 1232076feeaf21f2b264ae3c6e578efyre12663fe6ad2c94ec5a242609a28be21290047737414f73b8e70da2aa0ccb23ac91f227e03454ce1e3feaef41a03afa
            ACCESS_TOKEN_EXP: 2000s
